class OffensivePlayerGame:
    def __init__(self, name, opponent):
        self.name           = name
        self.opponent       = opponent
        self.passAtt        = 0
        self.passCmp        = 0
        self.passYds        = 0
        self.passYPA        = 0.0
        self.passTD         = 0
        self.interceptions  = 0
        self.passLG         = ""
        self.sack           = 0
        self.loss           = 0
        self.rate           = 0.0
        self.rushAtt        = 0
        self.rushYds        = 0
        self.rushAvg        = 0.0
        self.rushLg         = ""
        self.rushTD         = 0
        self.rushFirstDowns = 0
        self.rec            = 0
        self.recYds         = 0
        self.recAvg         = 0.0
        self.recLg          = ""
        self.recTD          = 0
        self.recFirstDowns  = 0
        self.YAC            = 0.0
        self.puntReturns    = 0
        self.puntReturnYds  = 0
        self.puntReturnAvg  = 0.0
        self.puntFC         = 0
        self.puntLG         = ""
        self.puntTD         = 0
        self.kickReturns    = 0
        self.kickReturnYds  = 0
        self.kickReturnAvg  = 0
        self.kickFC         = 0
        self.kickLG         = ""
        self.kickTD         = 0
        self.fum            = 0
        self.lost           = 0
        self.forced         = 0
        self.own            = 0
        self.opp            = 0
        self.tot            = 0
        self.yds            = 0
        self.fumTD          = 0

    def printOffensivePlayerGame(self):
        print(self.name,                ", ",
		  self.opponent,        ", ",
                  self.passAtt,         ", ",
                  self.passCmp,         ", ",
                  self.passYds,         ", ",
                  self.passYPA,         ", ",
                  self.passTD,          ", ",
                  self.interceptions,   ", ",
                  self.passLG,          ", ",
                  self.sack,            ", ",
                  self.loss,            ", ",
                  self.rate,            ", ",
                  self.rushAtt,         ", ",
                  self.rushYds,         ", ",
                  self.rushAvg,         ", ",
                  self.rushLg,          ", ",
                  self.rushTD,          ", ",
                  self.rushFirstDowns,  ", ",
                  self.rec,             ", ",
                  self.recYds,          ", ",
                  self.recAvg,          ", ",
                  self.recLg,           ", ",
                  self.recTD,           ", ",
                  self.recFirstDowns,   ", ",
                  self.YAC,             ", ",
                  self.puntReturns,     ", ",
                  self.puntReturnYds,   ", ",
                  self.puntReturnAvg,   ", ",
                  self.puntFC,          ", ",
                  self.puntLG,          ", ",
                  self.puntTD,          ", ",
                  self.kickReturns,     ", ",
                  self.kickReturnYds,   ", ",
                  self.kickReturnAvg,   ", ",
                  self.kickFC,          ", ",
                  self.kickLG,          ", ",
                  self.kickTD,          ", ",
                  self.fum,             ", ",
                  self.lost,            ", ",
                  self.forced,          ", ",
                  self.own,             ", ",
                  self.opp,             ", ",
                  self.tot,             ", ",
                  self.yds,             ", ",
                  self.fumTD),          ", "
